### ISSUE TITLE
Can't get it to work in an ionic project - possibly typescript related?

### ISSUE THREAD

**Issue by rbt074** [googleapis/nodejs-vision#240]
Hi,

I am trying to test this in a simple ionic project, but as soon as I include in a project it fails with:

TypeError: Cannot read property 'prototype' of undefined
    at patch (http://localhost:8100/build/vendor.js:230900:54)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:230761:18)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:230998:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:230701:10)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.module.exports (http://localhost:8100/build/vendor.js:230633:18)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.module.exports (http://localhost:8100/build/vendor.js:148017:17)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

#### Environment details

  - Windows 10
  - Node.js version: 9.3.0
  - npm version: 5.6.0
  - `@google-cloud/vision` version: v0.22.1

#### Steps to reproduce
 0 . install ionic/cordova: $ npm install -g ionic cordova
  1. ionic start (just generate a simple tab project) 
  2. add to page home.ts above @Component decorator: (probably better to make a provider instead but it failes never the less)

// Imports the Google Cloud client library
import vision from '@google-cloud/vision'; // or require depending on typescript version
const client = new vision.ImageAnnotatorClient();

3. ionic serve

I am not an expert in any way but this gets me stuck wanting to try it out with using HTTP calls myself as I have seen others doing in ionic projects.

Thanks!

Robert

**Comment by JustinBeckwith** [comment]
Greetings!  The library doesn't currently support webpack :/  We are tracking this over in #216
