### ISSUE TITLE
Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead

### ISSUE THREAD

**Issue by wdrfxy** [googleapis/nodejs-vision#350]
(node:12744) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
TypeError: Channel's second argument must be a ChannelCredentials
    at ServiceClient.Client (/home/wdrfxy/blockchain-explorer/node_modules/grpc/src/client.js:410:23)
    at new ServiceClient (/home/wdrfxy/blockchain-explorer/node_modules/grpc/src/client.js:936:12)
    at new AdminPeer (/home/wdrfxy/blockchain-explorer/app/platform/fabric/AdminPeer.js:65:30)
    at FabricClient.newAdminPeer (/home/wdrfxy/blockchain-explorer/app/platform/fabric/FabricClient.js:546:25)
    at FabricClient.initializeChannelFromDiscover (/home/wdrfxy/blockchain-explorer/app/platform/fabric/FabricClient.js:499:38)
    at <anonymous>
Received kill signal, shutting down gracefully
Closed out connections

**Comment by callmehiphop** [comment]
Hi @gholu-soul could you provide us with an example of how to trigger this error?

**Comment by bcoe** [comment]
@gholu-soul just following up, are you continuing to bump into this issue? If possible could you provide us with the specific API call that is giving you the error.
