### ISSUE TITLE
Header field "authorization" must only have a single value

### ISSUE THREAD

**Issue by CarlosUvaSilva** [googleapis/nodejs-vision#391]
#### Environment details

  - OS: MacOs
  - Node.js version: 11
  - npm version: 6.5
  - `@google-cloud/vision` version: 1.0

#### Steps to reproduce

I've been using release 0.25 of `@google-cloud/vision` successfully for while but when I updated to v1.0 it stopped working and I can't figure why

```
import vision from '@google-cloud/vision'

const credentials = require('../assets/ocr-credentials.json');
const clientOCR = new vision.ImageAnnotatorClient({credentials})

const request = {
      image: {
        content: data,
      },
      feature: {
        type: "TEXT_DETECTION"
      }
    }

export function callVisionOcr(request) {
  return new Promise((resolve, reject) => {
    clientOCR.documentTextDetection(request)
```

this was working before with 0.25 but now it works the first time I hit my API but after that it throws this error: 

```
"message": {
    "code": "ERR_HTTP2_HEADER_SINGLE_VALUE",
    "details": "Getting metadata from plugin failed with error: Header field \"authorization\" must only have a single value",
    "metadata": {
      "internalRepr": []
    },
    "note": "Exception occurred in retry method that was not classified as transient"
  }
```
Any help would be appreciated
Thanks!

**Comment by alexander-fenster** [comment]
It looks like it's a bug in `@grpc/grpc-js` v0.4.1 that is our dependency. This bad version already got unpublished. Please `rm -rf node_modules` and re-run `npm install`, double checking that `grep version node_modules/google-gax/node_modules/@grpc/grpc-js/package.json` shows v0.4.0 and not v0.4.1. Thanks!

**Comment by CarlosUvaSilva** [comment]
Hello @alexander-fenster thank you for the quick answer. Your fix worked 👍

**Comment by tcha-tcho** [comment]
It looks that this problem is back:
```
✔  functions: Using node@10 from host.
✔  functions: Emulator running at http://localhost:5001
i  functions: Beginning execution of "getSpaces"
⚠  Default "firebase-admin" instance created!
⚠  The Cloud Firestore emulator is not running so database operations will fail with a 'default credentials' error.
⚠  Google API requested!
   - URL: "https://www.googleapis.com/oauth2/v4/token"
   - Be careful, this may be a production service.
>  (node:20785) UnhandledPromiseRejectionWarning: Error: Getting metadata from plugin failed with error: Header field "authorization" must only have a single value
>      at Http2CallStream.call.on (/Users/malpelibook/Documents/codes/unnon/functions/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
>      at Http2CallStream.emit (events.js:194:15)
>      at process.nextTick (/Users/malpelibook/Documents/codes/unnon/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
>      at process._tickCallback (internal/process/next_tick.js:61:11)
>  (node:20785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
>  (node:20785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My package.json

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "@google-cloud/logging": "^5.2.1",
    "@google-cloud/storage": "^3.1.0",
    "@google-cloud/translate": "^4.1.3",
    "@google-cloud/vision": "^1.2.0",
    "child-process-promise": "^2.2.1",
    "city-timezones": "^1.1.0",
    "cloudinary": "^1.14.0",
    "cors": "^2.8.5",
    "country-language": "^0.1.7",
    "curl-request": "^1.1.1",
    "firebase": "^6.4.0",
    "firebase-admin": "^8.3.0",
    "firebase-functions": "^3.0.2",
    "firebase-functions-test": "^0.1.6",
    "firebase-tools": "^7.2.4",
    "glob": "^7.1.4",
    "grpc": "^1.23.1",
    "html-entities": "^1.2.1",
    "imgix-core-js": "^2.1.0",
    "mkdirp": "^0.5.1",
    "mkdirp-promise": "^5.0.1",
    "moniker": "^0.1.2",
    "node-emoji": "^1.10.0",
    "node-libcurl": "^2.0.1",
    "opengraph-io": "^1.1.2",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "stripe": "^7.8.0"
  },
  "engines": {
    "node": "10"
  },
  "private": true
}
```
I also take a look on the `call.js` and it seems that it came from a `@grpc/grpc-js@0.5.2`.

Thank you for any help! :)
