### ISSUE TITLE
Object Localization with B64 image

### ISSUE THREAD

**Issue by badman-rodriguez** [googleapis/nodejs-vision#556]
**Env Details**
  - Node.js version: v12.14.1
  - npm version: 6.14.0
    "@google-cloud/vision": "^1.10.0"

**Problem**
Was attempting to use the object localization functionality with a b64 encoded image... but always encountered an error

```js
 const request = {
    image: {
      content: b64, // b64 String
    },
  };

  const [result] = await client.objectLocalization(request);
  const objects = result.localizedObjectAnnotations;

  objects.forEach(object => {
    console.log(`Name: ${object.name}`);
    console.log(`Confidence: ${object.score}`);
    const vertices = object.boundingPoly.normalizedVertices;
    vertices.forEach(v => console.log(`x: ${v.x}, y:${v.y}`));
  });
```
Here is the image i was using and it is valid: https://jsfiddle.net/badmanrodriguez/ye8n0ms5/1/

But i always end up with this error:

```
(node:73133) UnhandledPromiseRejectionWarning: Error: invalid encoding
    at Object.decode (@protobufjs/base64/index.js:105:19)
    at Type.Image$fromObject [as fromObject] (eval at Codegen (@protobufjs/codegen/index.js:50:33), <anonymous>:9:15)
    at Type.fromObject (protobufjs/src/type.js:538:25)
    at Type.AnnotateImageRequest$fromObject [as fromObject] (eval at Codegen (@protobufjs/codegen/index.js:50:33), <anonymous>:10:20)
    at Type.fromObject (protobufjs/src/type.js:538:25)
    at Type.BatchAnnotateImagesRequest$fromObject [as fromObject] (eval at Codegen (@protobufjs/codegen/index.js:50:33), <anonymous>:14:26)
    at Type.fromObject (protobufjs/src/type.js:538:25)
    at serialize (@grpc/proto-loader/build/src/index.js:71:27)
    at ServiceClientImpl.makeUnaryRequest (@grpc/grpc-js/build/src/client.js:127:25)
    at ServiceClientImpl.<anonymous> (@grpc/grpc-js/build/src/make-client.js:92:19)
```

Any help with this would be amazing! Thanks in advance!

**Comment by vishald123** [comment]
Greetings @badman-rodriguez, how are you converting the image to base64 string? You can try the following way 
```js
    const img = fs.readFileSync('./duck_and_truck.jpg'); //YOUR IMAGE
    const encoded = Buffer.from(bimg).toString('base64'); //BASE64 ENCODED STRING
```
You can refer the [documentation](https://cloud.google.com/vision/docs/base64) for more info.

**Comment by badman-rodriguez** [comment]
Yes, i saw that.
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

`the result attribute contains the data as a data: URL representing the file's data as a base64 encoded string.`

Im currently sending to the server a b64 string, but will change it to send the file instead and convert it and see if that works.

**Comment by badman-rodriguez** [comment]
?

**Comment by vinnysenthil** [comment]
Closing this issue as the thread has been inactive for over a year. Please re-open if this is still an active issue.
