### ISSUE TITLE
Example code for `textDetection` is incorrect

### ISSUE THREAD

**Issue by bensooraj** [googleapis/nodejs-vision#60]
Following is the example code under the [`textDetection`](https://cloud.google.com/nodejs/docs/reference/vision/0.19.x/v1.ImageAnnotatorClient#textDetection) method:

```javascript
var image = {
  source: {imageUri: 'gs://path/to/image.jpg'}
};
vision.textDetection(image).then(response => {
  // doThingsWith(response);
  console.log(response); // I added this portion; not part of the example.
}).catch(err => {
  console.error(err);
});
```
Running the above example, throws the following error trace:

```
Error: No image present.
    at _coerceRequest (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/vision/src/helpers.js:69:21)
    at ImageAnnotatorClient.<anonymous> (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/vision/src/helpers.js:224:12)
    at ImageAnnotatorClient.wrapper [as annotateImage] (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/common/src/util.js:749:29)
    at ImageAnnotatorClient.<anonymous> (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/vision/src/helpers.js:141:17)
    at /Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/common/src/util.js:780:22
    at new Promise (<anonymous>)
    at ImageAnnotatorClient.wrapper [as textDetection] (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/@google-cloud/common/src/util.js:764:12)
    at /Users/Bensooraj/Desktop/NodeJS_Play/nisome/routes/index.js:40:10
    at Layer.handle [as handle_request] (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Bensooraj/Desktop/NodeJS_Play/nisome/node_modules/express/lib/router/route.js:137:13)
```

The above error came in from here:
https://github.com/googleapis/nodejs-vision/blob/8e042dc15dd82ab41f549e001368202b072c3d81/src/helpers.js#L68-L69

where the `request` object is expected to nest an `image` object within as mentioned in the documentation:

<img width="1221" alt="screen shot 2018-05-04 at 5 14 32 pm" src="https://user-images.githubusercontent.com/10161260/39626279-ddc86790-4fbe-11e8-89fb-44461ea73a72.png">

This is what worked for me:

```javascript
// Imports the Google Cloud client library
const vision = require('@google-cloud/vision');
// Creates a client
const client = new vision.ImageAnnotatorClient();
// Uploaded image, available in base64Image format,
// is converted to a Buffer
let imageBuffer = Buffer.from(req.body.base64Image, 'base64');

// Call the Cloud Vision client, to detect text
client
    .textDetection({
      image: { content: imageBuffer }
    }).then(response => {
      console.log(response);
    }).catch(err => {
      console.error(err);
    });
```

I believe the example code in the document should change to:

```javascript
const request = {
  image: {source: {imageUri: 'gs://path/to/image.jpg'}},
};
// OR, if you are using an image buffer
// const request = {
//   image: { content: imageBuffer }
// };

vision.textDetection(request).then(response => {
  // doThingsWith(response);
  console.log(response); // I added this portion; not part of the example.
}).catch(err => {
  console.error(err);
});
```

Or,

```javascript
let image = {
  source: {imageUri: 'gs://path/to/image.jpg'}
};
// OR, if you are using an image buffer
// let image = {
//   content: imageBuffer
// };
vision.textDetection({ image }).then(response => {
  // doThingsWith(response);
}).catch(err => {
  console.error(err);
});
```

#### Environment details
  - OS: System Version: macOS 10.12.6 (16G29) | Kernel Version: Darwin 16.7.0
  - Node.js version: v9.2.0
  - npm version: 6.0.0
  - `@google-cloud/vision` version: 0.19.0

**Comment by kinwa91** [comment]
Yes, you're right. It's a bug in the sample code.

**Comment by JustinBeckwith** [comment]
@alexander-fenster if the generated sample code is bad, what do we do?

**Comment by alexander-fenster** [comment]
Discussed it with @kinwa91 offline. This file, `src/helpers.js`, is a manually written wrapper, it's not auto-generated. So the error should be fixed in this file, no other changes are required.

As a rule of thumb, the generated code always lives inside `src/v*`. Within `src/`, only `src/index.js` can be auto-generated (or can be manually written, it's quite easy to tell by looking at the file and its edit history).
