### ISSUE TITLE
GRPC version wrong on node v9 or 10

### ISSUE THREAD

**Issue by zackify** [googleapis/nodejs-vision#61]
#### Environment details

  - OS: Mac (but using docker)
  - Node.js version: 8, 9, 10
  - npm version:
  - `@google-cloud/vision` version: 0.19.0

#### Steps to reproduce

  1. Set the node version to v9.0.0 OR v10.0.0
  2. npm install this library
  3. Copy the example code into a js file, run that file
  4. you get the below output

```
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v59-linux-x64-glibc
Found: [node-v57-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/app/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/grpc/src/client_interceptors.js:145:12)
    at Module._compile (module.js:641:30)
```

Have to use node v8 for this to actually work

**Comment by stephenplusplus** [comment]
I believe this will be addressed by https://github.com/googleapis/nodejs-common-grpc/issues/44 -- I'll close this issue and tag you over there so you can follow along. (If I'm wrong about the connection, let me know, and I can re-open here).
