### ISSUE TITLE
Firebase Function: Image moderator

### ISSUE THREAD

**Issue by rajflutter** [googleapis/nodejs-vision#831]
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'Reader' of undefined
at /Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:28:29
at /Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:22:26
at Object. (/Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:24:3)
at Module._compile (internal/modules/cjs/loader.js:959:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
at Function.Module._load (internal/modules/cjs/loader.js:727:14)
at Module.require (internal/modules/cjs/loader.js:852:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object. (/Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/src/index.js:52:16)

**Comment by conman0552** [comment]
Can confirm I am getting a similar issue.

TypeError: Cannot read property 'Reader' of undefined
    at E:\FearPromotionBot\node_modules\@google-cloud\vision\build\protos\protos.js:28:29
    at E:\FearPromotionBot\node_modules\@google-cloud\vision\build\protos\protos.js:22:26
    at Object.<anonymous> (E:\FearPromotionBot\node_modules\@google-cloud\vision\build\protos\protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\FearPromotionBot\node_modules\@google-cloud\vision\build\src\index.js:52:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\FearPromotionBot\commands\ocr.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

Not sure how you'd go about fixing it.

**Comment by munkhuushmgl** [comment]
It might be related to protobuf or some other update on packages. 
I would suggest you guys to remove all existing package-lock.json and node_modules directories. Then, update the library version to the latest.

```
rm package-lock.json
rm -rf node_modules
```

**Comment by conman0552** [comment]
> It might be related to protobuf or some other update on packages.
> I would suggest you guys to remove all existing package-lock.json and node_modules directories. Then, update the library version to the latest.
> 
> ```
> rm package-lock.json
> rm -rf node_modules
> ```

This fixed it. Note rm -rf node_modules was not a command on node (not sure what went on there) but removing package-lock.json and updating EVERY dependency fixed the issue.
